/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dependabot.test;

import org.apache.commons.lang3.StringUtils;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        System.out.println(StringUtils.indexOf("ffoo", "oo"));
    }
}
